version: "3"
services:
  profile-service:
    restart: always
    build:
      context: ./profile-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./profile-service:/app
    env_file: ./profile-service/.env.development
  auth-service:
    restart: always
    build:
      context: ./auth-service
      dockerfile: Dockerfile.dev
    ports: 
      - "5000:5000"
    volumes:
      - ./auth-service:/app
    env_file: ./auth-service/.env.development
  mongo:
    restart: always
    image: mongo
    ports:
      - "27017:27017"