FROM rust:1.58-buster as generator
WORKDIR /app
COPY . .

RUN cargo build
RUN mkdir ./data/
RUN cargo run --bin mongo

FROM mongo:5.0

COPY . .
COPY --from=generator ./app/data/ ./data/

RUN ["chmod", "+x", "./init.sh"]
CMD ./init.sh